"""empty message

Revision ID: 25801a711793
Revises: 0c46fec81e10
Create Date: 2019-10-31 10:35:52.388720

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '25801a711793'
down_revision = '0c46fec81e10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'artist_date_end')
    op.drop_column('Artist', 'artist_date_begin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('artist_date_begin', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('artist_date_end', postgresql.TIME(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
