"""empty message

Revision ID: 33e0c6660af9
Revises: f82532cd0c00
Create Date: 2019-10-29 17:23:50.744890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33e0c6660af9'
down_revision = 'f82532cd0c00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_talent')
    # ### end Alembic commands ###
