"""empty message

Revision ID: 5849ba5eddaa
Revises: 9ec510b17460
Create Date: 2019-10-31 10:10:21.364315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5849ba5eddaa'
down_revision = '9ec510b17460'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('artist_date_begin', sa.Time(), nullable=True))
    op.add_column('Artist', sa.Column('artist_date_end', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'artist_date_end')
    op.drop_column('Artist', 'artist_date_begin')
    # ### end Alembic commands ###
